# -*- coding: utf-8 -*-
"""download1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUYncUvBKCeLrob1fuxHi7a-kjr8lIqX
"""

pip install streamlit



import streamlit as st
import google.generativeai as genai

# Page config
st.set_page_config(page_title="Gemini Chatbot", layout="centered")

st.title("🤖 Gemini Chatbot")

# API Key (secure)
api_key = st.text_input("AIzaSyA-AuinhMhaLP5BygvkQ2Zzg2E5YSeoUl0", type="password")

if api_key:
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("Gemini 2.5 Flash")

    user_input = st.text_input("Ask something")

    if st.button("Send"):
        response = model.generate_content(user_input)
        st.success(response.text)



