# -*- coding: utf-8 -*-
"""download.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUYncUvBKCeLrob1fuxHi7a-kjr8lIqX
"""

pip install -q google-generativeai

import google.generativeai as genai

genai.configure(api_key="AIzaSyA-AuinhMhaLP5BygvkQ2Zzg2E5YSeoUl0")

model = genai.GenerativeModel("gemini-2.5-flash")

print("🤖 Gemini Chatbot (type 'exit' to stop)\n")

while True:
    user_input = input("You: ")

    if user_input.lower() == "exit":
        print("Chat ended.")
        break

    response = model.generate_content(user_input)
    print("Gemini:", response.text)

