# -*- coding: utf-8 -*-
"""gemini chatbot  123.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wVK2ykRM4EBzL5ZLibKoDsT794xxPqNV
"""

!pip install -q google-generativeai

import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyA-AuinhMhaLP5BygvkQ2Zzg2E5YSeoUl0"

import google.generativeai as genai
import os

# Configure Gemini
genai.configure(api_key=os.getenv("AIzaSyA-AuinhMhaLP5BygvkQ2Zzg2E5YSeoUl0"))

# Load Gemini model
model = genai.GenerativeModel("gemini-2.5-flash")

# Start chat session
chat = model.start_chat(history=[])

print("🤖 Gemini Chatbot")
print("Type 'exit' to stop\n")

while True:
    user_input = input("You: ")

    if user_input.lower() == "exit":
        print("👋 Chat ended")
        break

    response = chat.send_message(user_input)
    print("Bot:", response.text)
    print("-" * 50)





