# -*- coding: utf-8 -*-
"""heart disease by ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2kb3tPIPnut7O3TK00o0alBopW3iHFr
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_excel("heart.xlsx")
print(df.head())

df.head(0)

df.describe()

df.isnull().sum()

plt.figure(figsize=(6,4))
sns.countplot(x="target", data=df)
plt.title("Heart Disease Distribution")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.show()

X = df.drop("target", axis=1)
y = df["target"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

sample = np.array([[52,1,0,125,212,0,1,168,0,1.0,2,0,2]])
sample = scaler.transform(sample)

prediction = model.predict(sample)

if prediction[0] == 1:
    print("⚠️ Heart Disease Detected")
else:
    print("✅ No Heart Disease")



from google.colab import drive
drive.mount('/content/drive')